spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflex_bank_prototype
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 4456

application:
  endpoint:
    statement: "/statement"
    offerSelect: "/offer/select"
    calculate: "/calculate"

