spring:
  application:
    name: deal
  datasource:
    url: jdbc:postgresql://localhost:5432/neoflex_bank_prototype
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 4456

application:
  endpoint:
    statement: "/statement"
    offer_select: "/offer/select"
    calculate: "/calculate"

