server:
  port: 4400

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: deal-service-statement-by-id
          uri: http://localhost:4456
          predicates:
            - Path=/deal/admin/statement/{statementId}
        - id: deal-service-all-statements
          uri: http://localhost:4456
          predicates:
            - Path=/deal/admin/statement
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *



