server:
  port: 4420

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: calculator-offers
          uri: http://localhost:4455
          predicates:
            - Path=/calculator/offers

        - id: calculator-calc
          uri: http://localhost:4455
          predicates:
            - Path=/calculator/calc

        - id: deal-service-statement-by-id
          uri: http://localhost:4456
          predicates:
            - Path=/deal/admin/statement/**

        - id: deal-service-all-statements
          uri: http://localhost:4456
          predicates:
            - Path=/deal/admin/statement

        - id: deal-statement
          uri: http://localhost:4456
          predicates:
            - Path=/deal/statement

        - id: deal-offer-select
          uri: http://localhost:4456
          predicates:
            - Path=/deal/offer/select

        - id: deal-calculate-statementId
          uri: http://localhost:4456
          predicates:
            - Path=/deal/calculate/**

        - id: deal-document-statementId-send
          uri: http://localhost:4456
          predicates:
            - Path=/deal/document/{statementId}/send

        - id: deal-document-statementId-sign
          uri: http://localhost:4456
          predicates:
            - Path=/deal/document/{statementId}/sign

        - id: deal-document-statementId-code
          uri: http://localhost:4456
          predicates:
            - Path=/deal/document/{statementId}/code

        - id: statement
          uri: http://localhost:4457
          predicates:
            - Path=/statement

        - id: statement-offer
          uri: http://localhost:4457
          predicates:
            - Path=/statement/offer
      default-filters:
        - AddResponseHeader=Access-Control-Allow-Origin, *

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4410/eureka/
