spring:
  application:
    name: calculator

loan:
  baseRate: 0.15

server:
  port: 4455

application:
  endpoint:
    offers: "/offers"
    calc: "/calc"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4410/eureka/
