spring:
  application:
    name: calculator

loan:
  baseRate: 0.15

server:
  port: 4455

application:
  endpoint:
    offers: "/offers"
    calc: "/calc"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:4410/eureka/
